- name: Install the correct web server for RHEL
  include_tasks: "{{ item }}"
  loop:
    - redhat_apache.yml
    - redhat_php.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  include_tasks: "{{ item }}"
  loop:
    - debian_apache.yml
    - debian_php.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Setup index.html
  template:
    src=index.html.j2
    dest=/var/www/html/index.html
  notify: enable apache
