apiVersion: apps/v1
kind: Deployment
metadata:
  name: web02
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: apache
      group: shared
  template:
    metadata:
      labels:
        app: apache
        group: shared
    spec:
      containers:
      - name: apache
        image: httpd
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: html
        configMap:
          name: web02-index-html
