# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.define "novinano"
  config.vm.hostname = "novinano"
  config.vm.box_check_update = true
  config.vm.network "forwarded_port", guest: 80, host: 18080, host_ip: "127.0.0.1"
  config.vm.network "public_network", :dev => 'enp6s0'
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.storage_pool_name = "Media"
  end
  config.vm.provision :shell, path: "bootstrap.sh"
end
